source 'http://rubygems.org'

gem 'sinatra'
gem 'thin'
gem 'require_all', '~> 3.0.0'
gem 'activerecord', '~> 5.2', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake' 
gem 'sqlite3'
gem 'bcrypt'
gem 'rack-flash3'
gem 'shotgun'
gem 'pry'
gem 'tux'
gem 'securerandom'
